name: CI

on:
  push: ~
  workflow_dispatch: ~

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - # Copies the repository files to the Action Runner
        name: Checkout Repository
        uses: actions/checkout@v4

      - # Installs Java and other necessary tools
        name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: zulu

      - # Runs unit and integration tests
        name: Run Tests
        run: mvn test
